### ISSUE TITLE
Feature request: errorBorder. 

### ISSUE THREAD

**Issue by nick-beznos** [DevCrew-io/material-text-fields#10]
Can you please add `InputBorder? errorBorder;` to to the FilledOrOutlinedTextTheme? 

It doesn't look nice when border color is not matching the color of error text.

**Comment by nick-beznos** [comment]
Tried creating pull request for it, but I don't  have the access

**Comment by WaseemAbbas-DevCrew** [comment]
Hello, @nick-beznos! I hope you are doing well. Thank you for the above feature request. Read [here](https://github.com/DevCrew-io/material-text-fields/blob/main/.github/CONTRIBUTING.md) how to open a PR.
